-- snowflake/governance/safe_views.sql
-- Safe views for Standard Edition (no masking policies)

CREATE OR REPLACE VIEW TASTY_BYTES_ANALYTICS.FINAL_ANALYTICS.V_CUSTOMER_SAFE(
  CUSTOMER_ID,
  SOURCE_SYSTEM,
  CREATED_AT
) WITH TAG (
  TASTY_BYTES_ANALYTICS.GOVERNANCE.DOMAIN='PLATFORM',
  TASTY_BYTES_ANALYTICS.GOVERNANCE.LAYER='GOVERNED',
  TASTY_BYTES_ANALYTICS.GOVERNANCE.OWNER_TEAM='DATA_PLATFORM',
  TASTY_BYTES_ANALYTICS.GOVERNANCE.SENSITIVITY='FREE_TEXT'
)
AS
SELECT
  CUSTOMER_ID,
  SOURCE_SYSTEM,
  CREATED_AT
FROM TASTY_BYTES_V2."foodtruck"."customer"
WHERE COALESCE(_SNOWFLAKE_DELETED, FALSE) = FALSE;

CREATE OR REPLACE VIEW TASTY_BYTES_ANALYTICS.FINAL_ANALYTICS.V_REVIEW_SAFE(
  REVIEW_ID,
  TRUCK_ID,
  REVIEW_TS,
  RATING,
  SOURCE,
  USEFUL_COUNT
) WITH TAG (
  TASTY_BYTES_ANALYTICS.GOVERNANCE.DOMAIN='PLATFORM',
  TASTY_BYTES_ANALYTICS.GOVERNANCE.LAYER='GOVERNED',
  TASTY_BYTES_ANALYTICS.GOVERNANCE.OWNER_TEAM='DATA_PLATFORM',
  TASTY_BYTES_ANALYTICS.GOVERNANCE.SENSITIVITY='FREE_TEXT'
)
AS
SELECT
  REVIEW_ID,
  TRUCK_ID,
  REVIEW_TS,
  RATING,
  SOURCE,
  USEFUL_COUNT
FROM TASTY_BYTES_V2."foodtruck"."review"
WHERE COALESCE(_SNOWFLAKE_DELETED, FALSE) = FALSE;
