-- snowflake/ingestion/kafka_pipeline.sql
-- Exact DDLs you provided (Kafka → Raw → Typed → Iceberg)

-- RAW (Bronze)
CREATE OR REPLACE TABLE TASTY_BYTES_ICEBERG_DB.FOODTRUCK.FOODTRUCK_EVENTS_RAW_V2 (
  RECORD_CONTENT VARIANT,
  RECORD_METADATA VARIANT
) WITH TAG (
  TASTY_BYTES_ANALYTICS.GOVERNANCE.DOMAIN='OPS_TELEMETRY',
  TASTY_BYTES_ANALYTICS.GOVERNANCE.LAYER='BRONZE',
  TASTY_BYTES_ANALYTICS.GOVERNANCE.OWNER_TEAM='DATA_PLATFORM',
  TASTY_BYTES_ANALYTICS.GOVERNANCE.SENSITIVITY='INTERNAL'
);

-- TYPED (Silver)
CREATE OR REPLACE TABLE TASTY_BYTES_ICEBERG_DB.FOODTRUCK.FOODTRUCK_EVENTS_TYPED (
  EVENT_TS TIMESTAMP_NTZ(6),
  TRUCK_ID VARCHAR(16777216),
  EVENT_TYPE VARCHAR(16777216),
  AMOUNT NUMBER(10,2),
  TOPIC VARCHAR(16777216),
  PARTITION NUMBER(10,0),
  OFFSET NUMBER(19,0),
  CREATE_TIME NUMBER(19,0),
  RN NUMBER(18,0)
) WITH TAG (
  TASTY_BYTES_ANALYTICS.GOVERNANCE.DOMAIN='OPS_TELEMETRY',
  TASTY_BYTES_ANALYTICS.GOVERNANCE.LAYER='SILVER',
  TASTY_BYTES_ANALYTICS.GOVERNANCE.OWNER_TEAM='DATA_PLATFORM',
  TASTY_BYTES_ANALYTICS.GOVERNANCE.SENSITIVITY='INTERNAL'
);

-- ICEBERG (Silver)
CREATE OR REPLACE ICEBERG TABLE TASTY_BYTES_ICEBERG_DB.FOODTRUCK.FOODTRUCK_EVENTS_ICEBERG (
  EVENT_TS TIMESTAMP_NTZ(6),
  TRUCK_ID STRING,
  EVENT_TYPE STRING,
  AMOUNT DECIMAL(10, 2),
  TOPIC STRING,
  PARTITION DECIMAL(10, 0),
  OFFSET DECIMAL(19, 0),
  CREATE_TIME DECIMAL(19, 0)
) WITH TAG (
  TASTY_BYTES_ANALYTICS.GOVERNANCE.DOMAIN='OPS_TELEMETRY',
  TASTY_BYTES_ANALYTICS.GOVERNANCE.LAYER='SILVER',
  TASTY_BYTES_ANALYTICS.GOVERNANCE.OWNER_TEAM='DATA_PLATFORM',
  TASTY_BYTES_ANALYTICS.GOVERNANCE.SENSITIVITY='INTERNAL'
)
EXTERNAL_VOLUME = 'TASTY_BYTES_ICEBERG_EXTERNAL_VOLUME'
CATALOG = 'SNOWFLAKE'
BASE_LOCATION = 'foodtruck_events_iceberg/';

-- Streams
CREATE OR REPLACE STREAM TASTY_BYTES_ICEBERG_DB.FOODTRUCK.FOODTRUCK_EVENTS_RAW_V2_STREAM
  ON TABLE TASTY_BYTES_ICEBERG_DB.FOODTRUCK.FOODTRUCK_EVENTS_RAW_V2;

CREATE OR REPLACE STREAM TASTY_BYTES_ICEBERG_DB.FOODTRUCK.FOODTRUCK_EVENTS_TYPED_STRM
  ON TABLE TASTY_BYTES_ICEBERG_DB.FOODTRUCK.FOODTRUCK_EVENTS_TYPED;

-- Tasks
CREATE OR REPLACE TASK TASTY_BYTES_ICEBERG_DB.FOODTRUCK.FOODTRUCK_EVENTS_TYPED_TASK
  WAREHOUSE=SNOWFLAKE_LEARNING_WH
  SCHEDULE='1 MINUTE'
AS
MERGE INTO TASTY_BYTES_ICEBERG_DB.FOODTRUCK.FOODTRUCK_EVENTS_TYPED t
USING (
  SELECT
    TRY_TO_TIMESTAMP_NTZ(
      COALESCE(
        RECORD_CONTENT:"EVENT_TS"::STRING,
        RECORD_CONTENT:"event_ts"::STRING
      )
    )                                         AS EVENT_TS,
    COALESCE(RECORD_CONTENT:"TRUCK_ID"::STRING,   RECORD_CONTENT:"truck_id"::STRING)   AS TRUCK_ID,
    COALESCE(RECORD_CONTENT:"EVENT_TYPE"::STRING, RECORD_CONTENT:"event_type"::STRING) AS EVENT_TYPE,
    COALESCE(RECORD_CONTENT:"AMOUNT"::NUMBER(10,2), RECORD_CONTENT:"amount"::NUMBER(10,2)) AS AMOUNT,
    RECORD_METADATA:"topic"::STRING            AS TOPIC,
    RECORD_METADATA:"partition"::NUMBER(10,0)  AS PARTITION,
    RECORD_METADATA:"offset"::NUMBER(19,0)     AS OFFSET,
    RECORD_METADATA:"CreateTime"::NUMBER(19,0) AS CREATE_TIME
  FROM TASTY_BYTES_ICEBERG_DB.FOODTRUCK.FOODTRUCK_EVENTS_RAW_V2_STREAM
) s
ON  t.TOPIC     = s.TOPIC
AND t.PARTITION = s.PARTITION
AND t.OFFSET    = s.OFFSET
WHEN NOT MATCHED THEN
  INSERT (EVENT_TS, TRUCK_ID, EVENT_TYPE, AMOUNT, TOPIC, PARTITION, OFFSET, CREATE_TIME)
  VALUES (s.EVENT_TS, s.TRUCK_ID, s.EVENT_TYPE, s.AMOUNT, s.TOPIC, s.PARTITION, s.OFFSET, s.CREATE_TIME);

CREATE OR REPLACE TASK TASTY_BYTES_ICEBERG_DB.FOODTRUCK.FOODTRUCK_EVENTS_ICEBERG_TASK
  WAREHOUSE=SNOWFLAKE_LEARNING_WH
  SCHEDULE='1 MINUTE'
AS
INSERT INTO TASTY_BYTES_ICEBERG_DB.FOODTRUCK.FOODTRUCK_EVENTS_ICEBERG
SELECT
  EVENT_TS, TRUCK_ID, EVENT_TYPE, AMOUNT, TOPIC, PARTITION, OFFSET, CREATE_TIME
FROM TASTY_BYTES_ICEBERG_DB.FOODTRUCK.FOODTRUCK_EVENTS_TYPED_STRM;

-- Enable tasks (manual for demo)
-- ALTER TASK ... RESUME;
